name: dw_bike_trips_client
description: dasd.ware BikeTrips Client

publish_to: "none"
version: 0.9.1

environment:
  sdk: ">=2.17.0 <=3.0.6"

dependencies:
  cupertino_icons: ^1.0.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  graphql_flutter: ^5.1.0
  intl: ^0.18.0
  jiffy: ^6.2.1
  jwt_decoder: ^2.0.1
  location: ^5.0.0
  provider: ^6.0.5
  sticky_grouped_list: ^3.1.0
  path_provider: ^2.0.11
  stack: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_launcher_name:
    git:
      url: https://github.com/ride4sun/flutter_launcher_name
      ref: "0.9.1"
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.png"

flutter_launcher_name:
  name: "DW BikeTrips"
