name: dw_bike_trips_client
description: dasd.ware BikeTrips Client

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_config: ^1.0.7
  flutter_svg: ^0.19.1
  graphql_flutter: ^3.0.0
  graphql_builder: ^1.0.0
  grouped_list: ^3.7.1
  jwt_decoder: ^1.0.3
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"
  stack: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.png"

flutter_launcher_name:
  name: "DW BikeTrips"
